file_format: "1.0-rc.2"

log_level: debug

propagator:
  composite:
    - tracecontext:
    - baggage:

# tracer_provider:
#   processors:
#     - simple:
#         exporter:
#           console:

tracer_provider:
  processors:
    - batch:
        exporter:
          otlp_http:
            endpoint: https://api.honeycomb.io/v1/traces
            headers:
              - name: x-honeycomb-team
                value: my-api-key

# meter_provider:
#   readers:
#       periodic:
#         interval: 60000
#         timeout: 30000
#         exporter:
#           otlp_grpc:
#             endpoint: api.honeycomb.io:443
#             headers:
#               - name: x-honeycomb-team
#                 value: my-api-key
#               - name: x-honeycomb-dataset
#                 value: my-metrics-dataset

# logger_provider:
#   processors:
#     - batch:
#         exporter:
#           otlp_http:
#             endpoint: https://api.honeycomb.io/v1/logs
#             headers:
#               - name: x-honeycomb-team
#                 value: my-api-key

# resource:
#   attributes:
#     - name: service.name
#       value: otel-config-example-app
#       type: string
#     - name: hey
#       value: girl
